### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [leovincentseles/nctu.zsh-theme#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by leovincentseles** [comment]
Thanks for your advice. I have add an appropriate LICENSE file to my project.

**Comment by unixorn** [comment]
Added it to the list, thanks!
